### ISSUE TITLE
fail install on ubuntu 14.10

### ISSUE THREAD

**Issue by kewogc** [jussi-kalliokoski/audiolib.js#96]
kew@dns:~/au$ sudo npm install audiolib

> cubeb@0.2.0 install /home/kew/au/node_modules/audiolib/node_modules/cubeb
> node-gyp rebuild

make: Вход в каталог `/home/kew/au/node_modules/audiolib/node_modules/cubeb/build'
  CXX(target) Release/obj.target/node-cubeb/src/common.o
  CXX(target) Release/obj.target/node-cubeb/src/constants.o
../src/constants.cpp:4:25: fatal error: cubeb/cubeb.h: Нет такого файла или каталога
 #include <cubeb/cubeb.h>
                         ^
compilation terminated.
make: *** [Release/obj.target/node-cubeb/src/constants.o] Ошибка 1
make: Выход из каталога`/home/kew/au/node_modules/audiolib/node_modules/cubeb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-36-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/kew/au/node_modules/audiolib/node_modules/cubeb
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! cubeb@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cubeb@0.2.0 install script.
npm ERR! This is most likely a problem with the cubeb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cubeb
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-36-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "audiolib"
npm ERR! cwd /home/kew/au
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by soundyogi** [comment]
Same here :( Any Ideas?
